version: '2'
services:
  hotelcontroller-app:
    image: hotelcontroller
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://hotelcontroller-mongodb:27018
      - SPRING_DATA_MONGODB_DATABASE=HotelController
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  hotelcontroller-mongodb:
    extends:
      file: mongodb.yml
      service: hotelcontroller-mongodb
