version: '2'
services:
  hotelcontroller-mongodb:
    image: mongo:4.2.7
    ports:
      - '27018:27017'
    # volumes:
    #     - ~/volumes/jhipster/HotelController/mongodb/:/data/db/
    environment:
      - MONGO_INITDB_ROOT_USERNAME={mongodb-username}
      - MONGO_INITDB_ROOT_PASSWORD={mongodb-password}
    volumes:
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
  adminmongo:
    image: mrvautin/adminmongo
    ports:
      - 8092:1234
    depends_on:
      - hotelcontroller-mongodb
    environment:
      - HOST=0.0.0.0
